"""init

Revision ID: 1769136224
Revises: 
Create Date: 2026-01-22 21:43:44.213286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1769136224'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('editionStmt', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('language', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('publicationStmt', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('respStmt', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('sourceDesc', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('textgroup', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('title', sa.String(), nullable=False))
    op.alter_column('documents', 'urn',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_unique_constraint(None, 'documents', ['urn'])
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'lang')
    op.alter_column('elements', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('elements', 'attributes',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('elements', 'idx',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('elements', 'tagname',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('elements', 'textpart_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('elements', 'urn',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_elements_document'), table_name='elements')
    op.drop_index(op.f('idx_elements_textpart'), table_name='elements')
    op.drop_constraint(None, 'elements', type_='foreignkey')
    op.drop_column('elements', 'textpart_urn')
    op.drop_column('elements', 'textpart_index')
    op.drop_column('elements', 'document_urn')
    op.alter_column('textparts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('textparts', 'document_urn',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('textparts', 'idx',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('textparts', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('textparts', 'n',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('textparts', 'subtype',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('textparts', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('textparts', 'urn',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_textparts_document'), table_name='textparts')
    op.alter_column('tokens', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('tokens', 'element_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tokens', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tokens', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tokens', 'textpart_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tokens', 'urn',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tokens', 'whitespace',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('idx_tokens_document'), table_name='tokens')
    op.drop_index(op.f('idx_tokens_element'), table_name='tokens')
    op.drop_index(op.f('idx_tokens_textpart'), table_name='tokens')
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_column('tokens', 'document_urn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('document_urn', sa.TEXT(), nullable=False))
    op.create_foreign_key(None, 'tokens', 'documents', ['document_urn'], ['urn'])
    op.create_index(op.f('idx_tokens_textpart'), 'tokens', ['textpart_id'], unique=False)
    op.create_index(op.f('idx_tokens_element'), 'tokens', ['element_id'], unique=False)
    op.create_index(op.f('idx_tokens_document'), 'tokens', ['document_urn'], unique=False)
    op.alter_column('tokens', 'whitespace',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tokens', 'urn',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tokens', 'textpart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tokens', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tokens', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tokens', 'element_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tokens', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_textparts_document'), 'textparts', ['document_urn'], unique=False)
    op.alter_column('textparts', 'urn',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('textparts', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('textparts', 'subtype',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('textparts', 'n',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('textparts', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('textparts', 'idx',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('textparts', 'document_urn',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('textparts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('elements', sa.Column('document_urn', sa.TEXT(), nullable=False))
    op.add_column('elements', sa.Column('textpart_index', sa.INTEGER(), nullable=True))
    op.add_column('elements', sa.Column('textpart_urn', sa.TEXT(), nullable=True))
    op.create_foreign_key(None, 'elements', 'documents', ['document_urn'], ['urn'])
    op.create_index(op.f('idx_elements_textpart'), 'elements', ['textpart_id'], unique=False)
    op.create_index(op.f('idx_elements_document'), 'elements', ['document_urn'], unique=False)
    op.alter_column('elements', 'urn',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('elements', 'textpart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('elements', 'tagname',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('elements', 'idx',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('elements', 'attributes',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('elements', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('documents', sa.Column('lang', sa.TEXT(), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_constraint(None, 'documents', type_='unique')
    op.alter_column('documents', 'urn',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('documents', 'title')
    op.drop_column('documents', 'textgroup')
    op.drop_column('documents', 'sourceDesc')
    op.drop_column('documents', 'respStmt')
    op.drop_column('documents', 'publicationStmt')
    op.drop_column('documents', 'language')
    op.drop_column('documents', 'editionStmt')
    op.drop_column('documents', 'id')
    # ### end Alembic commands ###
