"""init

Revision ID: 1769136687
Revises: 1769136224
Create Date: 2026-01-22 21:51:28.006435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1769136687'
down_revision: Union[str, Sequence[str], None] = '1769136224'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editionStmt', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('publicationStmt', sa.String(), nullable=False),
    sa.Column('respStmt', sa.String(), nullable=False),
    sa.Column('sourceDesc', sa.String(), nullable=False),
    sa.Column('textgroup', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urn')
    )
    op.create_table('textparts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_urn', sa.String(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('n', sa.String(), nullable=True),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('urn', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_urn'], ['documents.urn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urn')
    )
    op.create_table('elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('tagname', sa.String(), nullable=False),
    sa.Column('textpart_id', sa.Integer(), nullable=False),
    sa.Column('urn', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['textpart_id'], ['textparts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('textpart_id', sa.Integer(), nullable=False),
    sa.Column('urn', sa.String(), nullable=False),
    sa.Column('whitespace', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['textpart_id'], ['textparts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('elements')
    op.drop_table('textparts')
    op.drop_table('documents')
    # ### end Alembic commands ###
